log4j.rootLogger=,InfoFile,ErrorFile,Console
#\u5B9A\u4E49\u65E5\u5FD7\u8F93\u51FA\u76EE\u7684\u5730\u4E3A\u63A7\u5236\u53F0  
log4j.appender.Console=org.apache.log4j.ConsoleAppender
log4j.appender.Console.Target=System.out
log4j.appender.Console.Threshold = DEBUG 
#\u53EF\u4EE5\u7075\u6D3B\u5730\u6307\u5B9A\u65E5\u5FD7\u8F93\u51FA\u683C\u5F0F\uFF0C\u4E0B\u9762\u4E00\u884C\u662F\u6307\u5B9A\u5177\u4F53\u7684\u683C\u5F0F  
log4j.appender.Console.layout = org.apache.log4j.PatternLayout
log4j.appender.Console.layout.ConversionPattern=[%p] [%c] - %m%n

#\u6587\u4EF6\u5927\u5C0F\u5230\u8FBE\u6307\u5B9A\u5C3A\u5BF8\u7684\u65F6\u5019\u4EA7\u751F\u4E00\u4E2A\u65B0\u7684\u6587\u4EF6  
log4j.appender.ErrorFile = org.apache.log4j.RollingFileAppender  
#\u6307\u5B9A\u8F93\u51FA\u76EE\u5F55  
log4j.appender.ErrorFile.File = ${catalina.home}/logs/DataManage_error.log
#\u5B9A\u4E49\u6587\u4EF6\u6700\u5927\u5927\u5C0F  
log4j.appender.ErrorFile.MaxFileSize = 5MB  
# \u8F93\u51FA\u6240\u4EE5\u65E5\u5FD7\uFF0C\u5982\u679C\u6362\u6210DEBUG\u8868\u793A\u8F93\u51FADEBUG\u4EE5\u4E0A\u7EA7\u522B\u65E5\u5FD7  
log4j.appender.ErrorFile.Threshold = ERROR 
log4j.appender.InfoFile.Append = true 
log4j.appender.ErrorFile.layout = org.apache.log4j.PatternLayout  
log4j.appender.ErrorFile.layout.ConversionPattern =[%p] [%d{yyyy-MM-dd HH\:mm\:ss}] [%l] %m%n
log4j.appender.ErrorFile.MaxBackIndex=0

#\u6587\u4EF6\u5927\u5C0F\u5230\u8FBE\u6307\u5B9A\u5C3A\u5BF8\u7684\u65F6\u5019\u4EA7\u751F\u4E00\u4E2A\u65B0\u7684\u6587\u4EF6  
log4j.appender.WarnFile = org.apache.log4j.RollingFileAppender  
#\u6307\u5B9A\u8F93\u51FA\u76EE\u5F55  
log4j.appender.WarnFile.File = ${catalina.home}/logs/DataManage_warn.log
#\u5B9A\u4E49\u6587\u4EF6\u6700\u5927\u5927\u5C0F  
log4j.appender.WarnFile.MaxFileSize = 1MB 
# \u8F93\u51FA\u6240\u4EE5\u65E5\u5FD7\uFF0C\u5982\u679C\u6362\u6210DEBUG\u8868\u793A\u8F93\u51FADEBUG\u4EE5\u4E0A\u7EA7\u522B\u65E5\u5FD7  
log4j.appender.WarnFile.Threshold = WARN
log4j.appender.WarnFile.Append = false 
log4j.appender.WarnFile.layout = org.apache.log4j.PatternLayout  
log4j.appender.WarnFile.layout.ConversionPattern =[%p] [%d{yyyy-MM-dd HH\:mm\:ss}] [%c] %m%n

#\u6587\u4EF6\u5927\u5C0F\u5230\u8FBE\u6307\u5B9A\u5C3A\u5BF8\u7684\u65F6\u5019\u4EA7\u751F\u4E00\u4E2A\u65B0\u7684\u6587\u4EF6  
log4j.appender.InfoFile = org.apache.log4j.RollingFileAppender  
#\u6307\u5B9A\u8F93\u51FA\u76EE\u5F55  
log4j.appender.InfoFile.File = ${catalina.home}/logs/DataManage_info.log
#\u5B9A\u4E49\u6587\u4EF6\u6700\u5927\u5927\u5C0F  
log4j.appender.InfoFile.MaxFileSize = 10MB  
# \u8F93\u51FA\u6240\u4EE5\u65E5\u5FD7\uFF0C\u5982\u679C\u6362\u6210DEBUG\u8868\u793A\u8F93\u51FADEBUG\u4EE5\u4E0A\u7EA7\u522B\u65E5\u5FD7  
log4j.appender.InfoFile.Threshold = INFO
log4j.appender.InfoFile.layout = org.apache.log4j.PatternLayout  
log4j.appender.InfoFile.layout.ConversionPattern =[%p] [%d{yyyy-MM-dd HH\:mm\:ss}] [%l] %m%n

#\u6587\u4EF6\u5927\u5C0F\u5230\u8FBE\u6307\u5B9A\u5C3A\u5BF8\u7684\u65F6\u5019\u4EA7\u751F\u4E00\u4E2A\u65B0\u7684\u6587\u4EF6  
log4j.appender.DebugFile = org.apache.log4j.RollingFileAppender  
#\u6307\u5B9A\u8F93\u51FA\u76EE\u5F55  
log4j.appender.DebugFile.File = ${catalina.home}/logs/DataManage_debug.log
#\u5B9A\u4E49\u6587\u4EF6\u6700\u5927\u5927\u5C0F  
log4j.appender.DebugFile.MaxFileSize = 1MB  
# \u8F93\u51FA\u6240\u4EE5\u65E5\u5FD7\uFF0C\u5982\u679C\u6362\u6210DEBUG\u8868\u793A\u8F93\u51FADEBUG\u4EE5\u4E0A\u7EA7\u522B\u65E5\u5FD7  
log4j.appender.DebugFile.Threshold = Debug
log4j.appender.DebugFile.Append = false 
log4j.appender.DebugFile.layout = org.apache.log4j.PatternLayout  
log4j.appender.DebugFile.layout.ConversionPattern =[%p] [%d{yyyy-MM-dd HH\:mm\:ss}] [%c] %m%n

#\u89E3\u51B3zookeeper\u5FC3\u8DF3\u673A\u5236\u65E5\u5FD7\u4E0D\u65AD\u5237\u65B0\u95EE\u9898
log4j.logger.org.apache.zookeeper.ClientCnxn=OFF
#dubbo\u63A5\u53E3\u5FC3\u8DF3\u65E5\u5FD7\u5173\u95ED
log4j.logger.com.alibaba.dubbo.remoting.exchange.support.header.HeartBeatTask=OFF
#log4j.logger.com.alibaba.dubbo.remoting.exchange.support.header.HeartbeatHandler=OFF

#${catalina.home}/logs/logs_tomcat.log
#${webapp.root}WEB-INF/logs/Project.log
#${service:logPath}/app.log