-- Create table
CREATE TABLE `STANDARDIZE_OBJECT_RELATION` (
  `ID`          VARCHAR(32) NOT NULL COMMENT '表 id',
  `OBJECT_ID`   BIGINT NOT NULL COMMENT '数据集 id',
  `OBJECT_NAME` VARCHAR(80) NOT NULL COMMENT '数据名称',
  `TABLE_ID`    VARCHAR(40) NOT NULL COMMENT '标准编码',
  `PARENT_ID`   VARCHAR(32) COMMENT '当object_id原始汇聚，是：-1，否：关联的原始汇聚标准的object_id',
  `CREATE_TIME` DATETIME COMMENT '创建时间',
  `UPDATE_TIME` DATETIME COMMENT '更新时间'
) COMMENT='标准object关系表';

-- Create table
CREATE TABLE `STANDARDIZE_OBJECTFIELD_REL` (
  `SET_ID`              VARCHAR(32) NOT NULL COMMENT '数据集id',
  `ID`                  VARCHAR(32) NOT NULL COMMENT '数据项 id',
  `RECNO`               INT NOT NULL COMMENT '字段序号值',
  `COLUMN_NAME`         VARCHAR(100) COMMENT '字段名称',
  `GADSJ_FIELDID`       VARCHAR(40) COMMENT '数据元',
  `DICTIONARY_REF_ID`   VARCHAR(40) COMMENT '引用数据字典id',
  `DICTIONARY_REF`      VARCHAR(40) COMMENT '引用数据字典',
  `DICTIONARY_CONTENT_ID` VARCHAR(40) COMMENT '数据字典ID',
  `DICTIONARY_CONTENT`  VARCHAR(40) COMMENT '数据字典内容',
  `PARENT_ID`           VARCHAR(32) NOT NULL COMMENT '数据集 id,当object_id原始汇聚，是：-1，否：关联的原始汇聚标的object_id',
  `PARENT_COLUMN_NAME`  VARCHAR(100) COMMENT '对标字段名称',
  `CREATE_TIME`         DATETIME COMMENT '创建时间',
  `UPDATE_TIME`         DATETIME COMMENT '更新时间',
  `FIELDCHINESENAME`    VARCHAR(100) COMMENT '字段中文名称'
) COMMENT='标准objectfield关系表';

-- Create table
CREATE TABLE `DSM_LABEL_CODE_TABLE` (
  `LABEL_LEVEL` BIGINT NOT NULL COMMENT '标签代号',
  `LABEL_NAME`  VARCHAR(255) NOT NULL COMMENT '标签名称'
);

-- Create table
CREATE TABLE `DSM_ALL_CODE_DATA` (
  `ID`          VARCHAR(100) NOT NULL COMMENT '每个码值的唯一uuid',
  `CODE_ID`     VARCHAR(100) NOT NULL COMMENT '每种码值的id值',
  `CODE_VALUE`  VARCHAR(100) NOT NULL COMMENT '码值',
  `CODE_TEXT`   VARCHAR(100) NOT NULL COMMENT '码值含义',
  `MEMO`        VARCHAR(100) COMMENT '注释'
) COMMENT='所有的代码信息';

-- Create table
CREATE TABLE `STANDARDIZE_ORIGINAL_DICT` (
  `ID`                  VARCHAR(100) NOT NULL COMMENT '原始字典表id',
  `DICTIONARY_NAME`     VARCHAR(100) NOT NULL COMMENT '字典名称',
  `FACTURER_ID`         VARCHAR(40) NOT NULL COMMENT '厂商信息id',
  `FACTURER`            VARCHAR(100) NOT NULL COMMENT '厂商信息',
  `CREATE_DATE`         DATETIME COMMENT '创建日期',
  `CREATOR`             VARCHAR(100) COMMENT '创建人',
  `STANDARD_DICTIONARY` VARCHAR(50) COMMENT '对应标准字典',
  `STANDARD_DICTIONARY_ID` VARCHAR(50) COMMENT '标准字典编码',
  `MEMO`                VARCHAR(800) COMMENT '备注说明',
  `CREATE_TIME`         DATETIME COMMENT '创建时间',
  `UPDATE_TIME`         DATETIME COMMENT '更新时间'
);
ALTER TABLE STANDARDIZE_ORIGINAL_DICT
    ADD CONSTRAINT PK_ORIGINAL_DICTIONARIES PRIMARY KEY (ID);

-- Create table
CREATE TABLE `STANDARDIZE_ORIGINAL_D_F` (
  `GROUP_ID`                VARCHAR(100) NOT NULL COMMENT '原始字典表id',
  `ID`                      VARCHAR(100) NOT NULL COMMENT '字典代码项id',
  `RECNO`                   SMALLINT NOT NULL COMMENT '字段序号值',
  `CODE_VALTEXT`            VARCHAR(100) NOT NULL COMMENT '代码名称',
  `CODE_VALVALUE`           VARCHAR(50) NOT NULL COMMENT '代码值',
  `STANDARD_CODE_VALTEXT`   VARCHAR(100) NOT NULL COMMENT '对应标准代码名称',
  `STANDARD_CODE_VALVALUE`  VARCHAR(50) COMMENT '对应标准代码值',
  `CREATE_TIME`             DATETIME COMMENT '创建时间',
  `UPDATE_TIME`             DATETIME COMMENT '更新时间'
);
ALTER TABLE STANDARDIZE_ORIGINAL_D_F
    ADD FOREIGN KEY (GROUP_ID) REFERENCES STANDARDIZE_ORIGINAL_DICT (ID);

-- Create table
CREATE TABLE `DSM_MODULE_CREATED_OBJECT` (
  `TABLEID`     VARCHAR(200) NOT NULL COMMENT '表id',
  `MODULE_NAME` VARCHAR(500) NOT NULL COMMENT '模块名称',
  `CREATED_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `OBJECTID`    BIGINT COMMENT '对象id'
);

-- Create table
CREATE TABLE `DSM_DD_BDDM` (
  `DMZD`    VARCHAR(128) COMMENT '代码字段',
  `DMZDZWM` VARCHAR(128) COMMENT '代码字段中文名',
  `DM`      VARCHAR(128) COMMENT '代码',
  `DMMC`    VARCHAR(128) COMMENT '代码名称'
) COMMENT='地标';

-- Create table
CREATE TABLE `DSM_SOURCEINFO` (
  `ID`              VARCHAR(50) COMMENT '主键id',
  `CREATE_TIME`     DATETIME COMMENT '创建时间',
  `UPDATE_TIME`     DATETIME COMMENT '更新时间',
  `SOURCEPROTOCOL`  VARCHAR(200) COMMENT '来源数据协议',
  `TABLENAME`       VARCHAR(200) COMMENT '来源数据名(表英文名)',
  `SOURCESYSTEM`    VARCHAR(200) COMMENT '来源系统代码',
  `SOURCEFIRM`      VARCHAR(200) COMMENT '来源厂商',
  `DATANAME`        VARCHAR(200) COMMENT '来源数据名(表中文名)',
  `DATA_ID`         VARCHAR(200) COMMENT '数据源',
  `PROJECT_NAME`    VARCHAR(200) COMMENT '项目空间',
  `CENTER_NAME`     VARCHAR(200) COMMENT '数据中心名称',
  `CENTER_ID`       VARCHAR(200) COMMENT '数据中心id'
) COMMENT='来源信息表';

-- Create table
CREATE TABLE `DSM_SOURCE_FIELD_INFO` (
  `ID`              VARCHAR(50) COMMENT '主键id',
  `SOURCEINFOID`    VARCHAR(50) COMMENT 'SOURCEINFOID表的ID',
  `TABLEID`         VARCHAR(200) COMMENT '表英文名',
  `RESOURCEID`      VARCHAR(200) COMMENT '资源id',
  `FIELDNAME`       VARCHAR(200) COMMENT '字段英文名',
  `FIELDDESCRIPTION` VARCHAR(200) COMMENT '字段中文名（描述）',
  `FIELDTYPE`       VARCHAR(64) COMMENT '字段类型',
  `FIELDLENGTH`     VARCHAR(64) COMMENT '字段长度',
  `ISNONNULL`       VARCHAR(16) COMMENT '是否为空',
  `ISDELETED`       VARCHAR(16) COMMENT '是否已经删除',
  `ISPRIMARYKEY`    VARCHAR(16) COMMENT '是否为主键',
  `ISFOREIGNKEY`    VARCHAR(16) COMMENT '是否为外键',
  `INSERTTIME`      VARCHAR(128) COMMENT '插入时间',
  `UPDATETIME`      VARCHAR(128) COMMENT '更新时间',
  `DATABASEURL`     VARCHAR(128) COMMENT '数据库的URL',
  `SCHEMEID`        VARCHAR(128) COMMENT '数据库/项目名',
  `FIELDSOURCETYPE` TINYINT DEFAULT 0 COMMENT '1：是 0：否 默认值：0',
  `FIELDCODE`       VARCHAR(128) COMMENT '相似度分析获取到的元素编码 add20200818',
  `GADSJFIELDID`    VARCHAR(128) COMMENT '数据元内部标识符',
  `DETERMINERID`    VARCHAR(128) COMMENT '限定词id',
  `ELEMENTID`       VARCHAR(128) COMMENT '数据要素id'
) COMMENT='来源字段信息表';

-- Create table
CREATE TABLE `DSM_OBJECT_MANAGE_STANDARD` (
  `ID`      VARCHAR(50) COMMENT '组织分类ID',
  `VALUE`   VARCHAR(50) COMMENT '规范值',
  `TYPE`    VARCHAR(10) COMMENT '规范类型',
  `REMARKS` TEXT COMMENT '备注',
  `DELETED` VARCHAR(1) COMMENT '是否已删除(0:否;1:是)',
  `PARID`   VARCHAR(50) COMMENT '父级组织分类ID',
  `TEXT`    VARCHAR(200) COMMENT '组织分类名称'
) COMMENT='数据库对象管理规范';

-- Create table
CREATE TABLE `DSM_STANDARD_TABLE_CREATED` (
  `TABLE_NAME`          VARCHAR(100) NOT NULL COMMENT '在数据库中创建的表名',
  `TABLE_PROJECT`       VARCHAR(100) NOT NULL COMMENT '在数据库中创建的表对应的项目名',
  `TABLE_BASE`          VARCHAR(100) NOT NULL COMMENT '对应的数据库类型',
  `OBJECT_ID`           VARCHAR(100) COMMENT 'objectId',
  `ID`                  VARCHAR(100) NOT NULL COMMENT '自增主键ID',
  `CREATE_TIME`         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '表的创建时间',
  `TABLE_NAME_CH`       VARCHAR(100) COMMENT '表中文名',
  `DATA_CENTER_NAME`    VARCHAR(100) COMMENT '数据中心名',
  `DATA_RESOURCE_NAME`  VARCHAR(100) COMMENT '数据源名称'
) COMMENT='通过标准管理页面已经创建的表';

-- Create table
CREATE TABLE `DP_TABLE_ORGANIZATION_ASSETS_TEMP` (
    `SJXJBM`                      VARCHAR(50) COMMENT '表协议名',
    `NAME`                        VARCHAR(600) COMMENT '表中文名',
    `TABLE_NAME_EN`               VARCHAR(600) COMMENT '表英文名',
    `PRIMARY_DATASOURCE_CH`       VARCHAR(150) COMMENT '数据来源一级分类中文名',
    `SECONDARY_DATASOURCE_CH`     VARCHAR(150) COMMENT '数据来源二级分类中文名',
    `PRIMARY_ORGANIZATION_CH`     VARCHAR(150) COMMENT '数据组织一级分类中文名',
    `SECONDARY_ORGANIZATION_CH`   VARCHAR(150) COMMENT '数据组织二级分类中文名',
    `FACTOR_ONE_NAME`             VARCHAR(150) COMMENT '数据资源要素一级分类中文名',
    `FACTOR_TWO_NAME`             VARCHAR(150) COMMENT '数据资源要素二级分类中文名',
    `FACTOR_DETAILED_NAME`        VARCHAR(150) COMMENT '数据资源要素细目分类代码名称',
    `FACTOR_ATTRIBUTES_NAME`      VARCHAR(150) COMMENT '数据资源属性分类代码名称',
    `TABLE_ALL_COUNT`             BIGINT COMMENT '表数据总行数 到昨天分区',
    `TABLE_SIZE`                  BIGINT COMMENT '表数据总大小 到昨天分区 byte',
    `TABLE_PROJECT`               VARCHAR(150) COMMENT '表的项目名',
    `LIFE_CYCLE`                  VARCHAR(150) COMMENT '表的生命周期',
    `TABLE_TYPE`                  VARCHAR(150) COMMENT '表类型 odps/ads/',
    `YESTERDAY_COUNT`             BIGINT COMMENT '昨天分区的数据量',
    `PARTITION_MESSAGE`           VARCHAR(150) COMMENT '是否为分区表  0:分区表  1:不是分区表  -1：不确定是否为分区表',
    `AVERAGE_DAILY_VOLUME`        BIGINT COMMENT '日均数据量',
    `VALUE_RATE`                  DECIMAL(10,2) COMMENT '有值率',
    `NULL_RATE`                   DECIMAL(10,2) COMMENT '空值率',
    `TABLE_STATE`                 VARCHAR(150) COMMENT '状态  正常/异常',
    `UPDATE_TYPE`                 VARCHAR(150) COMMENT '全量/增量/',
    `STATISTICS_TIME`             DATETIME COMMENT '统计时间',
    `FREQUENCY`                   VARCHAR(650) COMMENT '最近一个月使用次数/总使用次数',
    `LIVETYPE`                    VARCHAR(650) COMMENT 'NONLIVING：死表 LIVING：活表',
    `REGISTER_STATE`              VARCHAR(255) DEFAULT '-1' COMMENT '注册状态 -1:未注册 1:已注册',
    `OBJECT_ID`                   VARCHAR(100) COMMENT 'object表中的objectid',
    `AVERAGE_DAILY_SIZE`          BIGINT COMMENT '日均数据大小',
    `OBJECT_STATE`                VARCHAR(50) COMMENT '停用，启用状态，1为启用',
    `THREE_ORGANIZATION_CH`       VARCHAR(150) COMMENT '数据组织三级分类中文名',
    `LABELS`                      VARCHAR(500) COMMENT '数据资源标签',
    `UPDATE_PERIOD`               VARCHAR(100) COMMENT '更新批次',
    `UPDATE_DATE`                 VARCHAR(100) COMMENT '更新周期',
    `DATARESOURCE_CODE`           VARCHAR(100) COMMENT '资源服务平台组织机构代码',
    `EXCEPTION_MESSAGE`           VARCHAR(100) COMMENT '异常信息',
    `LIFE_CYCLE_STATUS`           VARCHAR(50) COMMENT '生命周期审批状态',
    `LASTDATAMODIFIEDTIME`        VARCHAR(100) COMMENT '最后修改时间',
    `TABLECREATEDTIME`            VARCHAR(100) COMMENT '表创建时间',
    `PARTITION_NUM`               VARCHAR(255) COMMENT '分区数量',
    `LASTVISITEDTIME`             VARCHAR(255) COMMENT '最后访问时间',
    `TABLEUSECOUNTOFMONTH`        VARCHAR(255) COMMENT '月使用量',
    `RESOURCEID`                  VARCHAR(255) COMMENT '数据资源id，用于管理权限表',
    `THREELEVEL_ORGANIZATION_CH`  VARCHAR(200) COMMENT '数据组织三级分类中文名',
    `ORGANIZATION_ID_LAST_LEVEL`  VARCHAR(150) COMMENT '数据组织分类id(最后一级)',
    `DATASOURCE_LAST_LEVEL`       VARCHAR(150) COMMENT '数据来源分类id(最后一级)',
    `RES_NAME`                    VARCHAR(200) COMMENT '数据源名称',
    `ISSTANDARD`                  VARCHAR(100) COMMENT '是否对标',
    `ALARM_LEVEL`                 VARCHAR(100) COMMENT '告警级别',
    `SJZYBQ5`                     VARCHAR(50) COMMENT '数据资源标签5'
) COMMENT='表组织资产的相关数据';

-- Create table
CREATE TABLE `STANDARDIZE_OUTPUTOBJECT` (
  `OBJ_GUID`    VARCHAR(40) NOT NULL COMMENT '对象唯一标识',
  `OOBJ_GUID`   VARCHAR(40) NOT NULL COMMENT '输入对象唯一标识',
  `OOBJ_RESERVENAME_XML` TEXT NOT NULL COMMENT '对象英文扩展名XML',
  `OOBJ_TYPE`   INT NOT NULL COMMENT '对象类型',
  `OOBJ_MEMO`   VARCHAR(256) COMMENT '备注',
  `OOBJ_STATUS` INT DEFAULT 1 COMMENT '状态。0：禁用；1：启用。',
  `OOBJ_SOURCE` INT DEFAULT 0 NOT NULL COMMENT '各厂商专有协议，1：普天；2：汇智；3：三所；4：烽火；默认为0表示适用于所有厂商'
);
ALTER TABLE STANDARDIZE_OUTPUTOBJECT
    ADD CONSTRAINT PK_OUTPUTOBJECT PRIMARY KEY (OOBJ_GUID, OOBJ_SOURCE);
ALTER TABLE STANDARDIZE_OUTPUTOBJECT
    ADD CONSTRAINT UQ_OUTPUTOBJECT UNIQUE (OBJ_GUID);

-- Create table
CREATE TABLE `STANDARDIZE_OBJECT` (
  `SYS_ID`      INT NOT NULL COMMENT '系统代号',
  `OBJ_GUID`    VARCHAR(40) NOT NULL COMMENT '对象唯一标识',
  `OBJ_ENGNAME` VARCHAR(256) NOT NULL COMMENT '对象英文名',
  `OBJ_CHINAME` VARCHAR(256) NOT NULL COMMENT '对象中文名',
  `OBJ_MEMO`    VARCHAR(256) COMMENT '备注',
  `SYS_SOURCE`  INT DEFAULT 0 COMMENT '各厂商专有协议，1：普天；2：汇智；3：三所；4：烽火；默认为0表示适用于所有厂商',
  `DATA_ID`     VARCHAR(64) COMMENT '数据仓库的data_id数据，用于跳转到数据接入',
  `TABLE_ID`    VARCHAR(64) COMMENT '数据仓库的table_id数据，用于跳转到数据接入',
  `CENTER_ID`   VARCHAR(64) COMMENT '数据仓库的center_id数据，用于跳转到数据接入',
  `INSERT_DATE` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '数据的插入时间'
);
ALTER TABLE STANDARDIZE_OBJECT
    ADD CONSTRAINT PK_OBJECT PRIMARY KEY (OBJ_GUID);

-- Create table
CREATE TABLE `STANDARDIZE_INPUTOBJECTRELATE` (
  `IOBJ_GUID`   VARCHAR(40) NOT NULL COMMENT '与【输入协议表】主键对应',
  `OOBJ_GUID`   VARCHAR(40) NOT NULL COMMENT '与【输出协议表】主键对应',
  `IOR_GUID`    VARCHAR(40) NOT NULL COMMENT '输入对象关系唯一标识',
  `IOR_MEMO`    VARCHAR(256) COMMENT '备注',
  `IOR_STATUS`  INT DEFAULT 1 NOT NULL COMMENT '0：禁用；1：启用',
  `IOR_SOURCE`  INT DEFAULT 0 COMMENT '各厂商专有协议，1：普天；2：汇智；3：三所；4：烽火；默认为0表示适用于所有厂商'
);
alter table STANDARDIZE_INPUTOBJECTRELATE
    add constraint PK_INPUTOBJECTRELATE primary key (IOR_GUID);

-- Create table
CREATE TABLE `STANDARDIZE_INPUTOBJECT` (
  `OBJ_GUID`    VARCHAR(40) NOT NULL COMMENT '对象唯一标识',
  `IOBJ_GUID`   VARCHAR(40) NOT NULL COMMENT '输入对象唯一标识',
  `IOBJ_TYPE`   INT NOT NULL COMMENT '对象类型',
  `IOBJ_MODULE` VARCHAR(256) COMMENT '需要处理该协议的模块',
  `IOBJ_MEMO`   VARCHAR(256) COMMENT '备注',
  `IOBJ_STATUS` INT DEFAULT 1 COMMENT '状态。0：禁用；1：启用。',
  `IOBJ_SAVEAS` INT DEFAULT 0 COMMENT '是否另存。0：否；1：是。',
  `IOBJ_ENCODE` INT DEFAULT 0 COMMENT '编码 0:UTF8 1:GB2312 2:GBK',
  `IOBJ_SOURCE` INT DEFAULT 0 NOT NULL COMMENT '各厂商专有协议，1：普天；2：汇智；3：三所；4：烽火；默认为0表示适用于所有厂商',
  `IOBJ_ALLMATCH` INT DEFAULT 0 COMMENT '是否全中标。0：否；1：是。'
);
alter table STANDARDIZE_INPUTOBJECT
    add constraint PK_INPUTOBJECT primary key (IOBJ_GUID, IOBJ_SOURCE);
alter table STANDARDIZE_INPUTOBJECT
    add constraint UQ_INPUTOBJECT unique (OBJ_GUID);
