FROM jdk_x86:1.8.0_144
MAINTAINER wangdongwei <wangdongwei@synway.com>
ADD  dataRelation-V1.7.0-20210512.tar.gz /
WORKDIR dataRelation
EXPOSE 8123
ENTRYPOINT ["java", "-jar", "datarelation-V1.7.0-20210512.jar"]