FROM jdk_x86:1.8.0_144
MAINTAINER wangdongwei <wangdongwei@synway.com>
ADD  datastandardmanager-V1.7.0-20210512.tar.gz /
WORKDIR datastandardmanager
EXPOSE 8123
ENTRYPOINT ["java", "-jar", "datastandardmanager-V1.7.0-20210512.jar"]