#MyBatis
mybatis.configuration.call-setters-on-nulls=true

#logback
logging.config=classpath:logback-spring.xml
logging.level.com.synway.reconciliation.dao=debug

#pagehelper
pagehelper.reasonable=true
pagehelper.helperDialect=oracle

#是否是浙江下发  区分浙江下发对账和新疆对账
isIssue= true
#是否开启接口的权限校验
enableAuthorized=false

######################### 下发对账相关配置 ########################
#下发对账统计
issueReconStatisticsCron= 0 40 * * * ?
#定时发送任务相关信息
sendTaskInfoCron=0 10 * * * ?
#定时接收任务相关信息
consumerTaskInfoCron=0 20 * * * ?
#定时接收下发对账单
consumerIssueBillCron=0 0/2 * * * ?
#标准数据表名缓存
updateDataNameCache=0 0 0/2 * * ?
#当地行政区划名称
local="宁波市"
#当地行政区划编码
localCode= 330200
#kafka消费者组
groupId="nbIssueGroup"

######################### 接收账单相关配置 ########################
# 账单存放根路径
billPath= F:\\test\\ceshi
# 账单每个文件的最大量  100M 1024 * 1024 * 100
billFileMaxSize= 104857600
# 每个账单文件接收最大时长 5min 5 * 60 * 1000
billFileMaxTime= 300000
# 接收账单超时时间 单位： s
receiveBillExpireTime= 40
# 账单文件超时时间 单位： 天
billFileExpireTime= 30
# 定时读取账单文件入库
consumerBillSchedule= 0 50 * * * ?
# 处理实例账单数据
handelHistoryBillData= 10 10 0 * * ?
# 定时清理账单文件
cleanBillFile= 0 0 0 0/3 * ?
# 定时查看writer是否存活
checkWriterAlive= 0/10 * * * * ?

######################### 新疆对账相关配置 ########################
#定时从原始账单表汇总数据到账单表  间隔两小时这个别改因为每次汇总前两个小时的
summarizeBill= 0 0 0/2 * * ?
#定时按实例进行数据对账
dataReconByInstance=0 10 0/2 * * ?
#定时生成盘点对账单
buildInventoryBill= 0 20 0/2 * * ?
#定时进行数据账单统计
billDataStatistics=0 30 0/2 * * ?
#定时进行数据对账分析
billDataAnalysis=0 40 0/2 * * ?
#定时更新账单相关信息
updateDsDetectedTable= 0 15 * * * ?

