FROM jdk_x86:1.8.0_144
MAINTAINER wangdongwei <wangdongwei@synway.com>
ADD  datagovernance-V1.7.0-20210512.tar.gz /
WORKDIR datagovernance
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "datagovernance-V1.7.0-20210512.jar"]