######################### profile.active ########################
#spring.profiles.active=dev

#====================MyBatis========================

logging.config=classpath:logback-spring.xml
logging.level.com.synway.datastandardmanager.dao=debug
pagehelper.reasonable=true
pagehelper.helper-dialect=oracle